fraud_detection:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 
      user: FRAUD_USER
      password: 
      role: FRAUD_ENGINEER_ROLE
      database: FRAUD_DETECTION_DEV_DB
      warehouse: FRAUD_DETECTION_DEV_WH
      schema: RAW
      threads: 4
